# Generated by Django 4.2.3 on 2023-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="membership_id_for_import",
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name="Mitgliedschaftartkennung für Import"),
        ),
        migrations.AddField(
            model_name="user",
            name="membership_id",
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name="Mitgliedsnummer"),
        ),
    ]
