# Generated by Django 5.0.7 on 2024-07-25 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressort',
            name='head',
            field=models.ManyToManyField(blank=True, default=None, related_name='ressort_head', to=settings.AUTH_USER_MODEL, verbose_name='Leiter:in'),
        ),
    ]
