# Generated by Django 5.0 on 2024-03-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='club.membership', verbose_name='Mitgliedschaftsart'),
        ),
    ]
