# Generated by Django 4.2 on 2023-06-09 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iban',
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Mitgliedschaftsart'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='work_compensation',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Entschädigung pro Stunde in €'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='work_hours',
            field=models.IntegerField(verbose_name='Arbeitsstunden'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='work_hours_boat_owner',
            field=models.IntegerField(verbose_name='Arbeitsstunden Bootseigner:in'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='work_hours_club_boat_user',
            field=models.IntegerField(verbose_name='Arbeitsstunden Clubbootnutzer:in'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buchungskonto'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to=settings.AUTH_USER_MODEL, verbose_name='Vorstehende:r'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='is_accounting_resort',
            field=models.BooleanField(default=False, verbose_name='Buchhaltungsresort'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Resortname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_create_invoices',
            field=models.BooleanField(default=False, verbose_name='Nutzer darf Rechnungen erstellen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_boat_owner',
            field=models.BooleanField(default=False, verbose_name='Nutzer ist Bootseigner:in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_clubboat_user',
            field=models.BooleanField(default=False, verbose_name='Nutzer ist Clubbootnutzer:in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Lizenznummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='club.membership', verbose_name='Mitgliedschaftsart'),
        ),
    ]
