# Generated by Django 5.0.3 on 2024-03-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_user_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_type',
        ),
        migrations.CreateModel(
            name='MembershipYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Jahr')),
                ('work_hours_overwrite_activate', models.BooleanField(verbose_name='Arbeitsstunden überschreiben')),
                ('work_hours_overwrite', models.IntegerField(verbose_name='Arbeitsstunden (Überschreiben für ausgewähltes Jahr)')),
                ('work_hours_boat_owner_overwrite_activate', models.BooleanField(verbose_name='Arbeitsstunden Bootseigner:in überschreiben')),
                ('work_hours_boat_owner_overwrite', models.IntegerField(verbose_name='Arbeitsstunden Bootseigner:in (Überschreiben für ausgewähltes Jahr)')),
                ('work_hours_club_boat_user_overwrite_activate', models.BooleanField(verbose_name='Arbeitsstunden Clubbootnutzer:in überschreiben')),
                ('work_hours_club_boat_user_overwrite', models.IntegerField(verbose_name='Arbeitsstunden Clubbootnutzer:in (Überschreiben für ausgewähltes Jahr)')),
                ('work_compensation_overwrite_activate', models.BooleanField(verbose_name='Entschädigung pro Stunde in € überschreiben')),
                ('work_compensation_overwrite', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Entschädigung pro Stunde in € (Überschreiben für ausgewähltes Jahr)')),
                ('full_work_compensation', models.BooleanField(default=False, verbose_name='Vollständige Entschädigung erfolgt')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='club.membership', verbose_name='Mitgliedschaftsart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_years', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
        ),
    ]
