# Generated by Django 4.2.3 on 2023-09-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_membership_membership_id_for_import_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="club.membership",
                verbose_name="Mitgliedschaftsart",
            ),
        ),
    ]
