# Generated by Django 5.0.3 on 2024-03-28 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_user_membership_type_membershipyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressort',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
        migrations.RemoveField(
            model_name='ressort',
            name='head',
        ),
        migrations.AlterUniqueTogether(
            name='membershipyear',
            unique_together={('user', 'year')},
        ),
        migrations.AddField(
            model_name='ressort',
            name='head',
            field=models.ManyToManyField(related_name='ressort_head', to=settings.AUTH_USER_MODEL, verbose_name='Leiter:in'),
        ),
    ]
