# Generated by Django 5.2.5 on 2025-12-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_ressort_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipyear",
            name="is_boat_owner",
            field=models.BooleanField(
                default=False, verbose_name="Nutzer ist Bootseigner im Jahr"
            ),
        ),
        migrations.AddField(
            model_name="membershipyear",
            name="is_clubboat_user",
            field=models.BooleanField(
                default=False, verbose_name="Nutzer ist Clubbootnutzer im Jahr"
            ),
        ),
    ]
