# Generated by Django 5.0.3 on 2024-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_ressort_bank_account_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipyear',
            options={'verbose_name': 'Membership in year', 'verbose_name_plural': 'Memberships in years'},
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_compensation_overwrite',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_compensation_overwrite_activate',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_hours_boat_owner_overwrite',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_hours_boat_owner_overwrite_activate',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_hours_club_boat_user_overwrite',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_hours_club_boat_user_overwrite_activate',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_hours_overwrite',
        ),
        migrations.RemoveField(
            model_name='membershipyear',
            name='work_hours_overwrite_activate',
        ),
        migrations.AddField(
            model_name='membershipyear',
            name='work_compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Entschädigung pro Stunde in € (Überschreiben für ausgewähltes Jahr)'),
        ),
        migrations.AddField(
            model_name='membershipyear',
            name='work_hours',
            field=models.IntegerField(default=0, verbose_name='Arbeitsstunden (Überschreiben für ausgewähltes Jahr)'),
        ),
        migrations.AddField(
            model_name='membershipyear',
            name='work_hours_boat_owner',
            field=models.IntegerField(default=0, verbose_name='Arbeitsstunden Bootseigner:in (Überschreiben für ausgewähltes Jahr)'),
        ),
        migrations.AddField(
            model_name='membershipyear',
            name='work_hours_club_boat_user',
            field=models.IntegerField(default=0, verbose_name='Arbeitsstunden Clubbootnutzer:in (Überschreiben für ausgewähltes Jahr)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, null=True, verbose_name='Geburtstag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='Lizenznummer'),
            preserve_default=False,
        ),
    ]
