# Generated by Django 5.0.3 on 2024-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_membershipyear_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid_sub',
            field=models.UUIDField(blank=True, null=True, verbose_name='OpenID Sub'),
        ),
    ]
