# Generated by Django 5.0.3 on 2024-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_user_openid_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipyear',
            name='year',
            field=models.IntegerField(verbose_name='Jahr'),
        ),
    ]
