# Generated by Django 5.0.6 on 2024-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_alter_membershipyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Mitgliedsnummer'),
        ),
    ]
