# Generated by Django 5.0.6 on 2024-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_membership_internal_name_ressort_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='internal_name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Interner Name'),
        ),
        migrations.AlterField(
            model_name='ressort',
            name='internal_name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Interner Ressortname'),
        ),
    ]
