# Generated by Django 5.0.6 on 2024-06-13 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservableThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('all_can_reserve', models.BooleanField(default=False, verbose_name='Reservierbar von allen')),
            ],
            options={
                'verbose_name': 'Reservierbares Objekt',
                'verbose_name_plural': 'Reservierbare Objekte',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Beginn der Reservierung')),
                ('end', models.DateTimeField(verbose_name='Ende der Reservierung')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationflow.reservablething', verbose_name='Reservierungsobjekt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
            ],
            options={
                'verbose_name': 'Reservierung',
                'verbose_name_plural': 'Reservierungen',
            },
        ),
        migrations.CreateModel(
            name='ReservationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_name', models.CharField(default='', max_length=64)),
                ('description', models.TextField()),
                ('users', models.ManyToManyField(blank=True, default=None, related_name='reservation_groups', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:innen in Reservierungsgruppe')),
            ],
            options={
                'verbose_name': 'Reservierungsgruppe',
                'verbose_name_plural': 'Reservierungsgruppen',
            },
        ),
        migrations.AddField(
            model_name='reservablething',
            name='reservation_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationflow.reservationgroup', verbose_name='Reservierungsgruppe'),
        ),
    ]
