# Generated by Django 5.0.7 on 2024-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservablething',
            name='description',
            field=models.TextField(default='', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='reservationgroup',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
