# Generated by Django 4.2 on 2023-06-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservationflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservabelthing",
            options={"verbose_name": "Reservierbares Objekt", "verbose_name_plural": "Reservierbare Objekte"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"verbose_name": "Reservierung", "verbose_name_plural": "Reservierungen"},
        ),
        migrations.AlterModelOptions(
            name="reservationgroup",
            options={"verbose_name": "Reservierungsgruppe", "verbose_name_plural": "Reservierungsgruppen"},
        ),
        migrations.AlterModelOptions(
            name="reservationgroupmembership",
            options={
                "verbose_name": "Zugehörigkeit in Reservierungsgruppe",
                "verbose_name_plural": "Zugehörigkeiten in Reservierungsgruppen",
            },
        ),
        migrations.AddField(
            model_name="reservabelthing",
            name="all_can_reserve",
            field=models.BooleanField(default=False, verbose_name="Reservierbar von allen"),
        ),
        migrations.AlterField(
            model_name="reservabelthing",
            name="description",
            field=models.TextField(verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="reservabelthing",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="reservabelthing",
            name="reservation_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservationflow.reservationgroup", verbose_name="Reservierungsgruppe"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end",
            field=models.DateTimeField(verbose_name="Ende der Reservierung"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start",
            field=models.DateTimeField(verbose_name="Beginn der Reservierung"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="thing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservationflow.reservabelthing", verbose_name="Reservierungsobjekt"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Benutzer:in"),
        ),
        migrations.AlterField(
            model_name="reservationgroupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="reservationflow.reservationgroup",
                verbose_name="Reservierungsgruppe",
            ),
        ),
        migrations.AlterField(
            model_name="reservationgroupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_group_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer:innen",
            ),
        ),
    ]
