# Generated by Django 5.2.5 on 2025-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationflow', '0003_reservation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Bemerkung'),
        ),
    ]
