# Generated by Django 5.0 on 2024-03-02 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationflow', '0003_reservationgroup_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationgroup',
            name='users',
            field=models.ManyToManyField(related_name='reservation_groups', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:innen in Reservierungsgruppe'),
        ),
    ]
