# Generated by Django 5.0.2 on 2024-03-07 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationflow', '0005_alter_reservationgroup_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationgroup',
            name='internal_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='reservationgroup',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='reservation_groups', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:innen in Reservierungsgruppe'),
        ),
    ]
