version: '3.3'
services:
  clubapp-dev:
    container_name: clubapp-dev
    command: python3 /code/clubapp/manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=*
      - DEBUG=True

      - ENABLE_OIDC_LOGIN=True
      - ENABLE_DJANGO_LOGIN=True

      # login with keycloak
      # see http://{keycloakurl}:{port}/realms/{realm}/.well-known/openid-configuration 
      - OIDC_RP_CLIENT_ID=
      - OIDC_RP_CLIENT_SECRET=
      - OIDC_OP_AUTHORIZATION_ENDPOINT=
      - OIDC_OP_TOKEN_ENDPOINT=
      - OIDC_OP_USER_ENDPOINT=
      - OIDC_OP_JWKS_ENDPOINT=
      - OIDC_OP_LOGOUT_ENDPOINT=
      - LOGOUT_REDIRECT_URL=
      - KEYCLOAK_ACCOUNT_URL=

      # keycloak sync job
      - KC_URL=
      - KC_REALM=
      - KC_CLIENT_ID=
      - KC_CLIENT_SECRET=
      - KC_USERNAME=
      - KC_PASSWORD=
    volumes:
      - /code/.venv
      - ./:/code
      - ./data:/clubapp_data
volumes:
  data: