version: '3.3'
services:
  clubapp-dev:
    container_name: clubapp-dev
    command: python3 /code/clubapp/manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=*
      - DEBUG=True

      - ENABLE_OIDC_LOGIN=True
      - ENABLE_DJANGO_LOGIN=True

      # see http://{keycloakurl}:{port}/realms/{realm}/.well-known/openid-configuration
  
      - OIDC_RP_CLIENT_ID=clubapp-local
      - OIDC_RP_CLIENT_SECRET=bvSuLTfZypwiCjhgLW6zXFa5SkLNeBrR
      - OIDC_OP_AUTHORIZATION_ENDPOINT=http://localhost:28080/realms/master/protocol/openid-connect/auth
      - OIDC_OP_TOKEN_ENDPOINT=http://localhost:28080/realms/master/protocol/openid-connect/token
      - OIDC_OP_USER_ENDPOINT=http://localhost:28080/realms/master/protocol/openid-connect/userinfo
      - OIDC_OP_JWKS_ENDPOINT=http://localhost:28080/realms/master/protocol/openid-connect/certs
      - OIDC_OP_LOGOUT_ENDPOINT=http://localhost:28080/realms/master/protocol/openid-connect/logout
      - LOGOUT_REDIRECT_URL
      - KEYCLOAK_ACCOUNT_URL=http://localhost:28080/realms/master/account
    volumes:
      - ./:/code
      - ./data:/clubapp_data
volumes:
  data: