version: 1
disable_existing_loggers: False
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
formatters:
  default:
    format: '%(asctime)s [%(name)s] %(levelname)s %(message)s'
root:
  handlers: [console]
  level: INFO
loggers:
  django:
    handlers: [console]
    level: INFO
    propagate: True
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: True
  uvicorn.error:
    handlers: [console]
    level: INFO
    propagate: True
  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: True
