# Generated by Django 5.0.3 on 2024-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refundflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='annotation',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
