# Generated by Django 4.2 on 2023-06-13 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("club", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, verbose_name="Titel")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                ("date_time", models.DateTimeField(verbose_name="Datum und Uhrzeit")),
                ("max_duration", models.IntegerField(verbose_name="Maximale Dauer (in Minuten)")),
                ("max_participants", models.IntegerField(verbose_name="Maximale Teilnehmer:innenanzahl")),
                (
                    "ressort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="clubwork", to="club.ressort", verbose_name="Ressort"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubWorkParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, verbose_name="Titel")),
                ("date_time", models.DateTimeField(verbose_name="Datum und Uhrzeit")),
                ("duration", models.IntegerField(verbose_name="Dauer (in Minuten)")),
                ("approve_date", models.DateTimeField(auto_now_add=True, verbose_name="Genehmigt am")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_work",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Genehmigt von",
                    ),
                ),
                (
                    "clubwork",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="clubwork.clubwork",
                        verbose_name="Arbeitsdienst",
                    ),
                ),
                (
                    "ressort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubwork_participations",
                        to="club.ressort",
                        verbose_name="Ressort",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clubwork_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teilnehmer:in",
                    ),
                ),
            ],
        ),
    ]
