# Generated by Django 4.2 on 2023-05-31 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127)),
                ("description", models.TextField()),
                ("date_time", models.DateTimeField()),
                ("max_duration", models.IntegerField()),
                ("max_participants", models.IntegerField()),
                ("resort", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="clubwork", to="club.resort")),
            ],
        ),
        migrations.CreateModel(
            name="ClubWorkParticipation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127)),
                ("date_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("approve_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_work", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "clubwork",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, related_name="participations", to="clubwork.clubwork"
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="clubwork_participations", to="club.resort"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="clubwork_participations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
