# Generated by Django 5.0.6 on 2024-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubwork',
            name='async_date',
            field=models.BooleanField(default=False, verbose_name='Eigenständige Abarbeitung mit Terminplanung. Das Datum ist als Frist zu interpretieren.'),
        ),
    ]
