# Generated by Django 4.2 on 2023-06-09 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
        ('clubwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubwork',
            name='date_time',
            field=models.DateTimeField(verbose_name='Datum und Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='clubwork',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='clubwork',
            name='max_duration',
            field=models.IntegerField(verbose_name='Maximale Dauer (in Minuten)'),
        ),
        migrations.AlterField(
            model_name='clubwork',
            name='max_participants',
            field=models.IntegerField(verbose_name='Maximale Teilnehmer:innenanzahl'),
        ),
        migrations.AlterField(
            model_name='clubwork',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubwork', to='club.resort', verbose_name='Ressort'),
        ),
        migrations.AlterField(
            model_name='clubwork',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='approve_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Genehmigt am'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='clubwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='clubwork.clubwork', verbose_name='Arbeitsdienst'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='date_time',
            field=models.DateTimeField(verbose_name='Datum und Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='duration',
            field=models.IntegerField(verbose_name='Dauer (in Minuten)'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubwork_participations', to='club.resort', verbose_name='Ressort'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='title',
            field=models.CharField(max_length=127, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubwork_participations', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer:in'),
        ),
    ]
