# Generated by Django 5.0.3 on 2024-03-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubwork', '0002_alter_clubworkparticipation_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubworkparticipation',
            name='clubwork',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='clubwork.clubwork', verbose_name='Arbeitsdienst'),
        ),
    ]
