# Generated by Django 5.0.6 on 2024-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubwork', '0002_clubwork_async_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubworkparticipation',
            name='did_send_approve_hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubworkparticipation',
            name='did_send_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
