# Generated by Django 5.0.3 on 2024-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubwork', '0004_alter_clubworkparticipation_clubwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubworkparticipation',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Genehmigt'),
        ),
    ]
