name: "Setup Python Environment"
description: "Caching for Python venv"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Restore venv cache
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - name: Restore pip download cache
      uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Install dependencies
      run: pip install -r requirements-dev.txt
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'